name: Reset Status Check File

on:
  workflow_run:
    workflows: ["CI Pipeline - Build and Test", "Deploy - Waiting Approval then Deploy"]
    types:
      - completed

jobs:
  reset-status:
    runs-on: ubuntu-22.04

    steps:
      - name: Download Status Check File
        uses: actions/download-artifact@v3
        with:
          name: status-check
          path: ./status

      - name: Check if both pipelines completed
        id: check_pipelines
        run: |
          echo "Checking if both pipelines completed successfully..."
          CI_COMPLETED=$(jq -r '.workflow_runs[] | select(.name == "CI Pipeline - Build and Test") | .conclusion' $GITHUB_EVENT_PATH)
          DEPLOY_COMPLETED=$(jq -r '.workflow_runs[] | select(.name == "Deploy - Waiting Approval then Deploy") | .conclusion' $GITHUB_EVENT_PATH)
          if [ "$CI_COMPLETED" = "success" ] && [ "$DEPLOY_COMPLETED" = "success" ]; then
            echo "Both pipelines completed successfully."
            echo "reset_status=true" >> $GITHUB_ENV
          else
            echo "One or both pipelines did not complete successfully."
            echo "reset_status=false" >> $GITHUB_ENV

      - name: Reset status check file
        if: env.reset_status == 'true'
        run: echo "false" > status/status_check.txt

      - name: Upload Status Check File
        uses: actions/upload-artifact@v3
        with:
          name: status-check
          path: status/status_check.txt
