name: Reset Status Check File

on:
  workflow_run:
    workflows: ["CI Pipeline - Build and Test", "Deploy - Waiting Approval then Deploy"]
    types:
      - completed

jobs:
  reset-status:
    runs-on: ubuntu-22.04

    steps:
      - name: Download Status Check File
        uses: actions/download-artifact@v4
        with:
          name: status-check
          path: ./status

      - name: Check if both pipelines completed
        id: check_pipelines
        run: |
          CI_COMPLETED=$(jq '.jobs["update-code-version"].conclusion' $GITHUB_EVENT_PATH)
          DEPLOY_COMPLETED=$(jq '.jobs["deploy-on-github-pages"].conclusion' $GITHUB_EVENT_PATH)
          if [ "$CI_COMPLETED" = "success" ] && [ "$DEPLOY_COMPLETED" = "success" ]; then
            echo "Both pipelines completed successfully."
            echo "reset_status=true" > status_check.txt
          else
            echo "One or both pipelines did not complete successfully."
            echo "reset_status=false" > status_check.txt

      - name: Upload Status Check File
        uses: actions/upload-artifact@v4
        with:
          name: status-check
          path: status_check.txt

      - name: Reset status check file
        if: steps.check_pipelines.outputs.reset_status == 'true'
        run: echo "false" > status_check.txt
