name: Reset Status Check File

on:
  workflow_run:
    workflows: 
      - "CI Pipeline - Build and Test"
      - "Deploy - Waiting Approval then Deploy"
    types:
      - completed

jobs:
  reset-status:
    runs-on: ubuntu-22.04

    steps:
      - name: Check if both pipelines completed
        id: check_pipelines
        run: |
          CI_COMPLETED=$(jq -r '.workflow_runs[] | select(.name=="CI Pipeline - Build and Test") | .conclusion' $GITHUB_EVENT_PATH)
          DEPLOY_COMPLETED=$(jq -r '.workflow_runs[] | select(.name=="Deploy - Waiting Approval then Deploy") | .conclusion' $GITHUB_EVENT_PATH)
          
          if [ "$CI_COMPLETED" = "success" ]; then
            echo "CI pipeline completed successfully."
          else
            echo "CI pipeline did not complete successfully."
          fi

          if [ "$DEPLOY_COMPLETED" = "success" ]; then
            echo "Deploy pipeline completed successfully."
            echo "reset_status=true" > status_check.txt
          elif [ -z "$DEPLOY_COMPLETED" ]; then
            echo "Deploy pipeline was not run."
            echo "reset_status=true" > status_check.txt
          else
            echo "Deploy pipeline did not complete successfully."
            echo "reset_status=false" > status_check.txt
          fi

      - name: Download Status Check File
        uses: actions/download-artifact@v4
        with:
          name: status-check
          path: ./status      

      - name: Upload Status Check File
        uses: actions/upload-artifact@v4
        with:
          name: status-check
          path: status_check.txt

      - name: Reset status check file
        if: steps.check_pipelines.outputs.reset_status == 'true'
        run: echo "false" > status_check.txt
