name: Setup Environment

on: [push]

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          fetch-depth: 1

    - name: Create .env file
      run: |
        echo "VUE_APP_SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> .env

    - name: Upload .env file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: env-file
        path: .env
