name: CI Pipeline - Waiting Approval then Deploy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Do you approve the deployment?'
        required: true
        default: 'yes'

jobs:

  deploy-on-github-pages:
  
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Build
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
