name: Deploy - Waiting Approval then Deploy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Do you approve the deployment?'
        options:
          - 'yes'
          - 'no'
        required: true
        default: 'no'

jobs:
  wait-for-status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Wait for status check
        id: check_status
        run: |
          echo "Checking status checks for the last commit..."
          REF=$(git rev-parse HEAD)
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          SUCCESS=false
          for i in {1..10}; do
            echo "Attempt $i: Checking status..."
            CHECK_RUNS=$(curl -s -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
              "https://api.github.com/repos/$OWNER/$REPO/commits/$REF/status")
            echo "CHECK_RUNS: $CHECK_RUNS"
            STATUS=$(echo "$CHECK_RUNS" | jq -r '.statuses[] | select(.context == "build-and-test-with-cache") | .state')
            if [ "$STATUS" = "success" ]; then
              SUCCESS=true
              break
            else
              echo "Current status: $STATUS"
              echo "Status check not yet successful. Waiting..."
              sleep 10
            fi
          done
          if [ "$SUCCESS" = false ]; then
            echo "Required status check 'build-and-test-with-cache' not found or not successful."
            exit 1
          fi
          echo "Status check successful."

  deploy-on-github-pages:
    runs-on: ubuntu-latest
    needs: [wait-for-status-check]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ env.KEY_CACHE }}
          restore-keys: |
            ${{ env.RESTORE_KEYS }}
            ${{ env.OS_VM }}
          upload-chunk-size: 262144

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
