name: Deploy - Waiting Approval then Deploy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

on:
  workflow_run:
    workflows: ["CI Pipeline - Build and Test"]
    types:
      - completed

jobs:
  wait-for-status-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Prompt for Deployment Approval
        id: approval
        run: |
          read -p "Do you approve the deployment? (yes/no): " approval
          echo "::set-output name=approved::${approval}"
        env:
          APPROVE: ${{ github.event.inputs.approve }}
        
      - name: Check Approval
        if: ${{ steps.approval.outputs.approved == 'yes' }}
        run: echo "Deployment Approved"
    
      - name: Checkout Repository
        if: ${{ steps.approval.outputs.approved == 'yes' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait for status check of build-and-test-with-cache (branch rule)
        if: env.new_commits == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          script: |
            const ref = 'heads/main'; // Certifique-se de que este é o ref correto para seu repositório
            const owner = context.repo.owner;
            const repo = context.repo.repo;
      
            // Adicionando logs para depuração
            console.log(`Checking status for ref: ${ref}, owner: ${owner}, repo: ${repo}`);
      
            const checkRuns = await github.rest.checks.listForRef({
              owner,
              repo,
              ref,
              status: 'completed'
            });
      
            // Adicionando logs para depuração
            console.log(`Total check runs found: ${checkRuns.data.total_count}`);
            if (checkRuns.data.total_count === 0) {
              throw new Error('No check runs found for the specified ref.');
            }
      
            // Listando todos os nomes de check runs para depuração
            const checkRunNames = checkRuns.data.check_runs.map(check => check.name);
            console.log('Check run names found:', checkRunNames);
      
            // Filtrando para encontrar o check run específico
            const statusChecks = checkRuns.data.check_runs.filter(
              (check) => check.name === 'build-and-test-with-cache'
            );
      
            // Adicionando logs para depuração
            console.log(`Total status checks for "build-and-test-with-cache" found: ${statusChecks.length}`);
            if (statusChecks.length === 0) {
              throw new Error('Required status check "build-and-test-with-cache" not found.');
            }
      
            const statusCheck = statusChecks[0];
      
            // Adicionando logs para depuração
            console.log(`Status check conclusion: ${statusCheck.conclusion}`);
            if (statusCheck.conclusion !== 'success') {
              throw new Error(`Status check "build-and-test-with-cache" has not passed. Conclusion: ${statusCheck.conclusion}`);
            } else {
              console.log('Status check "build-and-test-with-cache" passed successfully.');
            }
            
    outputs:
      approved: ${{ steps.approval.outputs.approved }}

  deploy-on-github-pages:
    needs: wait-for-status-check
    runs-on: ubuntu-latest
    steps:
      - name: Set up cache variables
        if: ${{ needs.wait-for-status-check.outputs.approved == 'yes' }}
        id: cache-vars
        run: |
          echo "Setting up cache variables..."
          echo "OS_VM=${{ runner.os }}-node-" >> $GITHUB_ENV
          echo "KEY_CACHE=${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json', '**/vitest.config.ts', '**/vite.config.ts', '**/tsconfig.vitest.json', '**/tsconfig.node.json', '**/tsconfig.json', '**/tsconfig.app.json', '**/env.d.ts', '**/src/main.ts', '**/src/router/index.ts', '**/update-version.cjs') }}" >> $GITHUB_ENV
          echo "RESTORE_KEYS=${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}" >> $GITHUB_ENV
          echo "Cache variables set."

      - name: Checkout Repository
        if: ${{ needs.wait-for-status-check.outputs.approved == 'yes' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node Environment
        if: ${{ needs.wait-for-status-check.outputs.approved == 'yes' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Cache node modules
        if: ${{ needs.wait-for-status-check.outputs.approved == 'yes' }}
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ env.KEY_CACHE }}
          restore-keys: |
            ${{ env.RESTORE_KEYS }}
            ${{ env.OS_VM }}
          upload-chunk-size: 262144

      - name: Install dependencies
        if: ${{ needs.wait-for-status-check.outputs.approved == 'yes' }}
        run: npm install

      - name: Audit and fix vulnerabilities
        if: ${{ needs.wait-for-status-check.outputs.approved == 'yes' }}
        run: npm audit fix

      - name: Run build
        if: ${{ needs.wait-for-status-check.outputs.approved == 'yes' }}
        run: npm run build
        
      - name: Deploy to GitHub Pages
        if: ${{ needs.wait-for-status-check.outputs.approved == 'yes' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
